# Week-3 Assignment: NumPy Basics  
**Study Plan:** A Journey to Data Analysis & Data Science - I  
**Assigned by:** Data Science & AI Community - RUET  



### Notebook Details  
**Author:** Audity Ghosh, CSE'17, RUET  
**First Opened:** 3 January 2025  
**Submitted:** 12 January 2025  



### Assignment Overview  
This assignment covers foundational skills in NumPy, focusing on array creation, indexing, slicing, reshaping, broadcasting, and basic statistical operations. It also includes a real-world problem-solving task related to sales data analysis.  

**Total Marks:** 60  


Importing necessary library

In [97]:
import numpy as np

1. Introduction to NumPy and Array Creation (10 Marks)
- Create a 1D NumPy array with the elements [10, 20, 30, 40, 50]. (2 Marks)
- Create a 2D array of shape (2, 3) using numpy.zeros. (3 Marks)
- Use numpy.linspace to create an array of 5 evenly spaced numbers between 0 and 100. (5 Marks)

In [98]:
#solution
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [99]:
#solution
arr_zeros = np.zeros([2,3], dtype=int) # assuring all elements are integer
print(arr_zeros) 

[[0 0 0]
 [0 0 0]]


In [100]:
#solution
arr_5 = np.linspace(0,100,num=5) #start = 0, end = 100, how many numbers? = 5
print(arr_5)

[  0.  25.  50.  75. 100.]


2. Array Indexing and Slicing (10 Marks)
- Using the 1D array [5, 10, 15, 20, 25, 30]:
- Extract the first 3 elements. (2 Marks)
- Extract every second element. (3 Marks)
- Change the 4th element to 50 and print the updated array. (5 Marks)

In [101]:

arr = np.array([5,10,15,20,25,30])
print(arr)

[ 5 10 15 20 25 30]


In [102]:
#solution
arr[:3] #extract only index 0 to 2

array([ 5, 10, 15])

In [103]:
#solution
arr[::2] # start default 0 index, end default last element, interval 2

array([ 5, 15, 25])

In [104]:
#solution
arr[3]=50 # 4th element is on index 3
print(arr)

[ 5 10 15 50 25 30]


3. Reshaping Arrays (10 Marks)
- Create a 1D array with 12 elements ranging from 1 to 12 using numpy.arange. (5 Marks)
- Reshape it into a 2D array of shape (3, 4). (5 Marks)


In [105]:
#solution
arr = np.arange(1,13) #as endpoint is not included, so added 13 to include 12
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [106]:
#solution
arr = arr.reshape([3,4])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


4. Broadcasting and Element-wise Operations (10 Marks)
- Create a 1D array with elements [1, 2, 3, 4, 5].
- Perform the following operations: <br>
-- Add 10 to each element. (2 Marks)<br>
-- Multiply each element by 3. (3 Marks)<br>
-- Calculate the square of each element. (5 Marks)<br>


In [107]:
#solution
arr = np.arange(1,6) #as endpoint is not included, so added 6 to include 5
print(arr)

[1 2 3 4 5]


In [108]:
#solution
arr = arr + 10 # adding 10 to each element
print(arr)

[11 12 13 14 15]


In [109]:
#solution
arr = arr * 3 # multiplying 3 to each element
print(arr)

[33 36 39 42 45]


In [110]:
#solution
arr = np.square(arr)
print(arr)

[1089 1296 1521 1764 2025]


5. Basic Statistics with Arrays (10 Marks)
- Create a NumPy array representing daily temperatures for a week: [30, 32, 31, 29, 28, 33, 34].
- Find the mean temperature of the week. (3 Marks)
- Find the minimum and maximum temperatures. (3 Marks)
- Calculate the total sum of the temperatures. (4 Marks)


In [111]:
#solution
temp = np.array([30,32,31,29,28,33,34])
print(temp)


[30 32 31 29 28 33 34]


In [112]:
#solution
temp.mean()

31.0

In [113]:
#solution
print(temp.min())
print(temp.max())

28
34


In [114]:
#solution
temp.sum()

217

6. Real-World Problem: Sales Analysis (10 Marks)
- Create a 2D array representing sales data for 2 products over 5 days:
Product 1: [200, 220, 250, 270, 300]  
Product 2: [150, 160, 170, 180, 200]  


- Calculate the total sales for each product. (4 Marks)
- Calculate the average sales per day. (3 Marks)
- Find the day with the highest sales for each product. (3 Marks)


In [115]:
#solution
sales_data = np.array([[200,220,250,270,300], [150,160,170,180,200]])
print(sales_data)

[[200 220 250 270 300]
 [150 160 170 180 200]]


In [116]:
#solution
total_sales_product1 = sales_data[0].sum()
print(total_sales_product1)
total_sales_product2 = sales_data[1].sum()
print(total_sales_product2)

1240
860


In [117]:
#solution

# Calculate the total sales for all products over all days
total_sales_5_days = np.sum(sales_data, axis=0)  # Sum along columns (axis=0), i.e., daily total sales

# Calculate the average sales per day
average_sales_per_day = np.mean(total_sales_5_days)  # Mean of daily total sales

# Display the result
print("Average sales per day:", average_sales_per_day)

# Calculate the average sales per day column-wise (mean along axis 0)
average_sales_per_day = np.mean(sales_data, axis=0)

# Display the result
print("Average sales per day (col-wise):", average_sales_per_day)

Average sales per day: 420.0
Average sales per day (col-wise): [175. 190. 210. 225. 250.]


In [118]:
#solution

# Find the day with the highest sales for Product 1 (index of max value)
product_1_highest_day = np.argmax(sales_data[0]) + 1  # Add 1 to convert to 1-based index

# Find the day with the highest sales for Product 2 (index of max value)
product_2_highest_day = np.argmax(sales_data[1]) + 1  # Add 1 to convert to 1-based index

# Display the results
print("Day with highest sales for Product 1:", product_1_highest_day)
print("Day with highest sales for Product 2:", product_2_highest_day)

Day with highest sales for Product 1: 5
Day with highest sales for Product 2: 5
